### ISSUE TITLE
Unable to test ARIA using React Testing Library 

### ISSUE THREAD

**Issue by ashleigh-yeoman** [woofers/react-dialog-polyfill#27]
[According to WAI-ARIA](https://www.w3.org/WAI/ARIA/apg/patterns/dialog-modal/#roles_states_properties), Modals need to have the role of `dialog`, but this polyfill doesn't enable that.

As you can see from [this repro](https://github.com/james-yeoman/react-dialog-polyfill-role-repro), React Testing Library isn't detecting the `dialog` role. Even when the `dialog` role is set on the polyfilled modal, RTL isn't detecting it.

What's strange is that when I set the `getByRole` options to include hidden roles, and change `toBeInTheDocument` to `toBeDefined`, there's a different error of `e.showModal is not a function`. So even if the role was a hidden role, I can't test for it because `getByRole` seems to cause the render to be treated differently.

Any insight you have of the polyfill would be greatly appreciated

**Comment by woofers** [comment]
Hi @james-yeoman, sorry for the delay in response.

The first issue from the repro is that the test does not await the click, and finishes before the actual modal opens.

The second issue after that is that jsdom does not support the `dialog` element, it only has stub definitions.  There is an open issue here: https://github.com/jsdom/jsdom/issues/3294.

As a result `getByRole` does not seem to recognize the element as having the dialog role.

Here is how I would re-write the test to ensure that the button click opens the modal and it renders the content/HTML:

```tsx
import { render, cleanup, screen, waitFor } from "@testing-library/react"
import App from "./App"
import { vi } from "vitest"

describe("Modal Aria Compliance", () => {
  beforeEach(() => {
    const modalRoot = document.getElementById("modal-root")
    HTMLDialogElement.prototype.showModal = vi.fn().mockImplementation(
        function mock(this: DialogElement) { this.open = true }
    )
    if (modalRoot) document.removeChild(modalRoot)
    document.body.innerHTML = `<div id="modal-root" />`
  })

  afterEach(() => {
    vi.resetAllMocks()
    cleanup()
  })

  test("Modal has the dialog role", async () => {
    render(<App />)
    const button = screen.getByTestId("modal-button")
    await button.click()
    await waitFor(() => {
      expect(screen.getByText("Hello everybody!")).toBeInTheDocument()
    })
    expect(screen.getByTestId("modal")).toBeInTheDocument()
    expect(screen.getByTestId("modal").open).toBe(true)
  })
})
```

You will also need to add `data-testid="modal"` to the Modal component.

This tests that:
1. The modal is opened after the button click
2. The content shows after the button click
3. The HTML exists in the document

Closing this issue as I can't do anything further to address this issue.
